### ISSUE TITLE
请所有支持匪共的程序员、网宣员型程序员滚出github

### ISSUE THREAD

**Issue by soulofc** [programthink/zhao#110]
很多自称“程序员”的人来发issue，要求关掉这个项目，关掉那个项目的，还美其名曰是为了让大陆程序员也能访问github，防止github被封掉。不管理由如何，其目标和匪共网络管控部门出奇的一致，无外乎就是这些项目结露了匪共高官的腐败和黑暗，打中七寸，戳中G点了，这让匪共如坐针毡，欲除之而后快，匪共在大陆控制舆论只有一个大招：封口，可惜在这里是西人美利坚老爷的网站，匪共使不上力，这时伪装的大陆程序员“民意”的招数用上了。借用墙内五毛常用的一句话：”觉得中国不好可以滚出去呀！“，对这些匪共走狗咱只想说：”这不是你家的网站，你觉得不好可以滚呀，别要求关这个关那个的，你以为是在匪共治下呀！“

**Comment by hcconquer** [comment]
一群键盘侠天天叫来叫去有什么用了？嫌妨害了github的人，github官方都没说什么，而且人家发布这个属于别人的自由，只要不违法就行，凭什么限制别人的权利？反对TG的人，手段要狠一点，要么学汪精卫去刺杀，要么学孙中山去募资搞颠覆，天天唧唧歪歪还能把TG叫垮台啊？
======================Best regards, Chen Han 韩琛======================

在 2016年11月20日，19:17，soulofc <notifications@github.com> 写道：很多自称“程序员”的人来发issue，要求关掉这个项目，关掉那个项目的，还美其名曰是为了让大陆程序员也能访问github，防止github被封掉。不管理由如何，其目标和匪共网络管控部门出奇的一致，无外乎就是这些项目结露了匪共高官的腐败和黑暗，打中七寸，戳中G点了，这让匪共如坐针毡，欲除之而后快，匪共在大陆控制舆论只有一个大招：封口，可惜在这里是西人美利坚老爷的网站，匪共使不上力，这时伪装的大陆程序员“民意”的招数用上了。借用墙内五毛常用的一句话：”觉得中国不好可以滚出去呀！“，对这些匪共走狗咱只想说：”这不是你家的网站，你觉得不好可以滚呀，别要求关这个关那个的，你以为是在匪共治下呀！“—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/programthink/zhao","title":"programthink/zhao","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/programthink/zhao" class="">https://github.com/programthink/zhao</a>" class=""><a href="https://github.com/programthink/zhao" class="">https://github.com/programthink/zhao</a></a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"请所有支持匪共的程序员、网宣员型程序员滚出github (#110)"}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/programthink/zhao/issues/110" class="">https://github.com/programthink/zhao/issues/110</a>" class=""><a href="https://github.com/programthink/zhao/issues/110" class="">https://github.com/programthink/zhao/issues/110</a></a>"}}}

**Comment by soulofc** [comment]
@hcconquer ，笔和文章也是扎向敌人心脏投枪和匕首。舆论一样是战场。

**Comment by archdevil0** [comment]
那些叫嚣关闭的支那豚不一定是支持共匪的，大多数支那豚在愚民教育下早就丧失了良知与人性，完全变成了一个精致的利己主义者。只是支那豚们的弱智大脑无法想到，当利己主义者越来越多时会怎么样。所有支那豚都只关注自己利益，所以就有那么多的雾霾，三鹿，雷洋。

**Comment by ilwgya** [comment]
好支威希！！！

**Comment by baoang** [comment]
这话挺应景的——这网站不是你家的，觉得不好可以滚出去。

**Comment by peerless2012** [comment]
楼主不也是xx的一条狗？见谁咬谁，你的良心就不会痛？

**Comment by Martwu** [comment]
@baoang 虽然被骂五毛，不过也支持你。

**Comment by Martwu** [comment]
我正是因为反对 @archdevil0 这种套帽子，人身攻击的，就被套成无毛了。

**Comment by ZZinKin** [comment]
大美利坚万岁，欧美洋人都是我们爹！

**Comment by levinit** [comment]
网站是你家开的？
你要发政见我管不着 但是我看到支那x三个字就恶心 有你这样人身攻击的？

**Comment by jacobcyl** [comment]
我敢打赌，博主如果当了国家首领，博主家的亲人朋友叔伯至亲，肯定不会腐败的，一定不会去做官，不会去做董事长的，肯定会去农田里面朝黄土背朝天，因为只有这样，博主就不会面临今天的这个局面，就不会有人也搞一个博主的家族关系链。

博主，我说的对不对，期待博主带领你的人民拿上枪杆子上街去，要是没有胆量，就拿个美分也好。

我不是五毛，我是自干五，就是干不惯你们这些人整天瞎哔哔，还一本正经站在人类制高点上，把我等屁民都当成奴才，当成我们已经限制了人生自由，把自己当成自由的天上人，站在最高处嘲笑我等屁民的“愚昧”，殊不知，屁民在乎什么。

**Comment by zzy1996** [comment]
@ZZinKin 不是谁都跟你一样奴性深入骨髓，到处给自己认爹。也不撒泡尿照照自己，你配姓赵吗

**Comment by fasthing** [comment]
@ zhangzhaoyuan30 不是谁都跟你一样当狗当出优越感，到处给自己认爹。也不撒泡尿照照自己，你配有皿煮吗？

**Comment by fasthing** [comment]
@zhangzhaoyuan30 不是谁都跟你一样当狗都能当上瘾，到处给自己认爹。也不撒泡尿照照自己，你配有皿煮吗？

**Comment by fasthing** [comment]
我不支持TG，但是我反感你这种傻逼，要滚也是你这种傻逼滚 懂吗？

**Comment by ZZinKin** [comment]
这个傻逼项目赶紧关闭吧，github不是给你们用来做政治宣传的，滚出github。

**Comment by posclegom** [comment]
@ZZinKin @fasthing 滚不滚不是你们说了算，是GitHub说了算。所以大家都洗洗睡吧。

**Comment by da-shen-anonym** [comment]
美国是我们的爸爸，要学会尊敬爸爸，多给爸爸磕头，为什么要给爸爸惹麻烦？把爸爸惹急了，Gist损失了多少流量？就不能得有点孝心吗？

**Comment by jupiterben** [comment]
觉得这个repo不好 可以滚啊 五毛不是天天这样讲么
